// Reports & Incidents
import { createIncident, getIncidents } from '../services/db.js';
import { showToast } from '../components/Toast.js';

export const Reports = {
    render: async (profile, _, uid) => {
        const incidents = await getIncidents(uid);
        return `
        <div class="page-header fade-in-up"><div class="page-header-row"><div><h1>Reports & Incident Management</h1><p>File security incidents, view reports, and track the national threat landscape.</p></div><button class="btn btn-primary" id="new-incident-btn"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg> Report Incident</button></div></div>

        <div class="dashboard-row-equal fade-in-up">
            <div class="card"><h3 class="mb-16">National Threat Summary</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><div style="padding:16px;background:var(--danger-muted);border-radius:var(--border-radius-sm);text-align:center"><div style="font-size:1.8rem;font-weight:800;color:var(--danger)">4,218</div><div style="font-size:0.7rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:1px">Phishing</div></div><div style="padding:16px;background:var(--warning-muted);border-radius:var(--border-radius-sm);text-align:center"><div style="font-size:1.8rem;font-weight:800;color:var(--warning)">892</div><div style="font-size:0.7rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:1px">Malware</div></div><div style="padding:16px;background:var(--info-muted);border-radius:var(--border-radius-sm);text-align:center"><div style="font-size:1.8rem;font-weight:800;color:var(--info)">347</div><div style="font-size:0.7rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:1px">Social Eng.</div></div><div style="padding:16px;background:var(--success-muted);border-radius:var(--border-radius-sm);text-align:center"><div style="font-size:1.8rem;font-weight:800;color:var(--success)">97.8%</div><div style="font-size:0.7rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:1px">Block Rate</div></div></div></div>
            <div class="card"><h3 class="mb-16">Your Filed Incidents (${incidents.length})</h3>${incidents.length > 0 ? `<div style="display:flex;flex-direction:column;gap:12px;max-height:300px;overflow-y:auto">${incidents.map(inc => `<div style="padding:12px 16px;background:var(--bg-secondary);border-radius:var(--border-radius-xs);border-left:3px solid ${inc.severity==='critical'?'var(--danger)':inc.severity==='high'?'var(--warning)':'var(--info)'}"><div class="flex-between"><span style="font-weight:600;font-size:0.85rem">${inc.title}</span><span class="badge badge-${inc.severity==='critical'?'danger':inc.severity==='high'?'warning':'info'}">${inc.severity}</span></div><div style="font-size:0.75rem;color:var(--text-muted);margin-top:4px">${new Date(inc.date).toLocaleDateString()} — ${inc.type}</div></div>`).join('')}</div>` : '<div style="text-align:center;padding:40px;color:var(--text-muted)"><div style="font-size:2rem;margin-bottom:8px">📁</div><p>No incidents filed yet.</p></div>'}</div>
        </div>

        <div class="card fade-in-up mt-24"><h3 class="mb-16">Threat Intelligence Feed</h3><div class="activity-feed"><div class="activity-item"><div class="activity-dot-col"><div class="activity-dot" style="background:var(--danger)"></div><div class="activity-line"></div></div><div class="activity-content"><div class="activity-title"><strong>APT-41 Campaign</strong> — Spear-phishing targeting govt energy sector</div><div class="activity-time">32m ago • NCD Threat Intel</div></div></div><div class="activity-item"><div class="activity-dot-col"><div class="activity-dot" style="background:var(--warning)"></div><div class="activity-line"></div></div><div class="activity-content"><div class="activity-title"><strong>CVE-2026-2847</strong> — Critical RCE in networking firmware</div><div class="activity-time">2h ago • CERT-In Advisory</div></div></div><div class="activity-item"><div class="activity-dot-col"><div class="activity-dot" style="background:var(--info)"></div><div class="activity-line"></div></div><div class="activity-content"><div class="activity-title"><strong>Ransomware Report Q1</strong> — 24% increase in state-sponsored ransomware</div><div class="activity-time">5h ago • NIB</div></div></div><div class="activity-item"><div class="activity-dot-col"><div class="activity-dot" style="background:var(--success)"></div></div><div class="activity-content"><div class="activity-title"><strong>Patch Deployment</strong> — All critical patches deployed</div><div class="activity-time">8h ago • NCD Ops</div></div></div></div></div>

        <!-- Modal -->
        <div id="incident-modal" class="modal-overlay"><div class="modal"><div class="modal-header"><h2>Report Security Incident</h2><button id="inc-close" class="modal-close">✕</button></div><form id="incident-form"><div class="form-group"><label class="form-label">Title *</label><input type="text" class="form-input" id="inc-title" placeholder="Brief description" required></div><div class="form-group"><label class="form-label">Type *</label><select class="form-select" id="inc-type" required><option value="">Select...</option><option>Phishing</option><option>Malware</option><option>Unauthorized Access</option><option>Data Breach</option><option>Social Engineering</option><option>Physical Security</option><option>Other</option></select></div><div class="form-group"><label class="form-label">Severity *</label><select class="form-select" id="inc-sev" required><option value="">Select...</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></div><div class="form-group"><label class="form-label">Description *</label><textarea class="form-textarea" id="inc-desc" placeholder="Detailed description..." required></textarea></div><div style="display:flex;gap:12px;justify-content:flex-end"><button type="button" id="inc-cancel" class="btn btn-secondary">Cancel</button><button type="submit" class="btn btn-primary">Submit Report</button></div></form></div></div>`;
    },
    afterRender: (profile, _, uid) => {
        const modal = document.getElementById('incident-modal');
        const close = () => modal.classList.remove('active');
        document.getElementById('new-incident-btn')?.addEventListener('click', () => modal.classList.add('active'));
        document.getElementById('inc-close')?.addEventListener('click', close);
        document.getElementById('inc-cancel')?.addEventListener('click', close);
        modal?.addEventListener('click', (e) => { if(e.target===modal) close(); });
        document.getElementById('incident-form')?.addEventListener('submit', async (e) => {
            e.preventDefault();
            await createIncident(uid, { title: document.getElementById('inc-title').value, type: document.getElementById('inc-type').value, severity: document.getElementById('inc-sev').value, description: document.getElementById('inc-desc').value, reportedByName: profile?.displayName || profile?.name });
            showToast('Incident reported! Security team notified.', 'success');
            close();
            window.location.hash = '#/reports';
        });
    }
};
